//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaGuineuData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clase
    {
        public int Id { get; set; }
        public Nullable<int> IdEstacion { get; set; }
        public Nullable<int> IdEscuela { get; set; }
        public Nullable<int> IdNivel { get; set; }
        public Nullable<bool> EsClub { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> HoraInicio { get; set; }
        public Nullable<double> HoraFin { get; set; }
        public Nullable<double> Duracion { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> Personas { get; set; }
        public Nullable<int> IdEdades { get; set; }
        public string Nombre { get; set; }
    }
}
