//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaGuineuData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaGuineuEntities : DbContext
    {
        public LaGuineuEntities()
            : base("name=LaGuineuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estacion> Estacion { get; set; }
        public virtual DbSet<Monitor> Monitor { get; set; }
        public virtual DbSet<Token> Token { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<MonitorDisponible> MonitorDisponible { get; set; }
        public virtual DbSet<MonitorEstacion> MonitorEstacion { get; set; }
        public virtual DbSet<MonitorTitulo> MonitorTitulo { get; set; }
        public virtual DbSet<Escuela> Escuela { get; set; }
        public virtual DbSet<Clase> Clase { get; set; }
        public virtual DbSet<ClaseCliente> ClaseCliente { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Nivel> Nivel { get; set; }
        public virtual DbSet<Club> Club { get; set; }
        public virtual DbSet<EscuelaCliente> EscuelaCliente { get; set; }
        public virtual DbSet<Deporte> Deporte { get; set; }
        public virtual DbSet<EscuelaDeporte> EscuelaDeporte { get; set; }
        public virtual DbSet<EscuelaEstacion> EscuelaEstacion { get; set; }
        public virtual DbSet<Titulo> Titulo { get; set; }
        public virtual DbSet<EscuelaDisponible> EscuelaDisponible { get; set; }
        public virtual DbSet<ClaseMonitor> ClaseMonitor { get; set; }
        public virtual DbSet<ClubCliente> ClubCliente { get; set; }
    }
}
